#!/usr/bin/env ruby

require "rbtune"
require "keychain"
require "optparse"

opt = OptionParser.new
opt.version = Rbtune::VERSION
opt.banner += <<"EOS"
 site station

 ラジオ配信サイトクラスと放送局コードを指定して、ラジオ放送を受信する。

    sites: #{Radio::bands * "|" }

EOS

opt.parse! ARGV
unless ARGV.size == 2
  puts opt.help
  exit 1
end
klass = Module.const_get(ARGV.shift)
radio = klass.new
unless radio.is_a? Radio
  puts "site #{klass} は正しくありません"
  exit 1
end

channel = ARGV.shift

begin
  if radio.is_a? RadikoPremium
    kc = KeyChain.new("http://radiko.jp")
    account, password = kc.account
    radio.login account, password
  end
  radio.open
  radio.tune channel
  radio.play

rescue Radio::HTTPForbiddenException
  puts 'ラジコプレミアムの認証に失敗しました。rbtune --set-authentication で正しいアカウントとパスワードを設定してください'

rescue Interrupt
  # do nothing

ensure
  radio.close
end
