#!/usr/bin/env ruby
# coding: utf-8

require "rbradi/version"
require "radiru"
require "radiko"
require "radiko_premium"
require "simul"
require "listenradio"

require "optparse"
require "pp"

channel = nil 
filename = nil 
min = 30 
# path = '/home/pi/radio'
quiet = false
wait = 0

account = "fusuian@gmail.com"
password =  "raradiko"

stations = Radio.bands.map { |radio| radio::channels.keys }.flatten!


opt = OptionParser.new
opt.version = Rbradi::VERSION
opt.on("-c channel_name","--channel", stations*'|'){|v| channel = v}
opt.on("-t [30]","--time", Float, "録音時間 (分）"){|v| min = v}
opt.on("-o ファイル名","--output","出力ファイル"){|v| filename = v}
opt.on("-w [0]", "--wait", Float, "録音開始までの待ち時間（秒）")
opt.on("-q", "--quiet", "録音時の同時再生を行わない" ) {|v| quiet = true}
opt.parse! ARGV

radio_class = Radio.bands.find { |tuner| tuner::channels[channel] }
raise "station #{channel} not found." unless radio_class

sec = min*60

radio = radio_class.new
radio.outdir = ENV['RADIODIR'] || '.'

begin
	radio.login account, password 
	radio.open
	radio.tune channel
	radio.play wait: wait, sec: sec, filename: filename, quiet: quiet

ensure
	radio.close
end
