#!/usr/bin/env ruby
# ラジオ配信サイトクラスと放送局コードを指定して、ラジオ放送を受信する。

require "rbradi/version"
require "radiru"
require "radiko"
require "radiko_premium"
require "simul"
require "listenradio"
require "keychain"
require "optparse"

opt = OptionParser.new
opt.version = Rbradi::VERSION
opt.banner += <<"EOS"
 site station

 ラジオ配信サイトクラスと放送局コードを指定して、ラジオ放送を受信する。

    sites and stations:
#{Radio::bands.map {|band| %Q(      #{band}: #{band::channels.keys*'|'})} *"\n" }

EOS

opt.parse! ARGV
unless ARGV.size == 2
  puts opt.help
  exit 1
end
klass = Module.const_get(ARGV.shift)
radio = klass.new
unless radio.is_a? Radio
  puts "site #{klass} は正しくありません"
  exit 1
end

channel = ARGV.shift
unless channel && radio.class.channels.include?(channel)
  puts "放送局コード #{channel} は登録されていません"
  exit 1
end

begin
  if radio.is_a? RadikoPremium
    kc = KeyChain.new("http://radiko.jp")
    account, password = kc.account
    radio.login account, password
  end
  radio.open
  radio.tune channel
  radio.play

rescue Radio::HTTPForbiddenException
  puts 'ラジコプレミアムの認証に失敗しました。--set-authentication オプションで正しいアカウントとパスワードを設定してください'

rescue Interrupt
  # do nothing

ensure
  radio.close
end
